Groupy/Controllers/HomeController.cs
using Groupy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupy.Controllers
{
    public class HomeController : Controller
    {
        GroupyEntities StoreDB = new GroupyEntities();
        private List<Item> GetTopSellingItems(int count)
        {
            return StoreDB.Items.OrderByDescending(i => i.OrderDetails.Count())
                .Take(count)
                .ToList();
        }
        public ActionResult Index()
        {
            var items = GetTopSellingItems(3);
            return View(items);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Groupy/Controllers/ShoppingCartController.cs
using Groupy.Models;
using Groupy.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupy.Controllers
{
    public class ShoppingCartController : Controller
    {
        GroupyEntities storeDB = new GroupyEntities();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);


            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            return View(viewModel);
        }
        public ActionResult AddToCart(int id)
        {

            var addedItem = storeDB.Items
                .Single(item => item.ItemId == id);


            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedItem);


            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {

            var cart = ShoppingCart.GetCart(this.HttpContext);


            string itemName = storeDB.Carts
                .Single(item => item.RecordId == id).Item.Title;


            int itemCount = cart.RemoveFromCart(id);


            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

Groupy/Controllers/StoreController.cs
using Groupy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Groupy.Controllers
{
    public class StoreController : Controller
    {
        GroupyEntities storeDB = new GroupyEntities();
        // GET: Store
        public ActionResult Index()
        {
            var categories = storeDB.Categories.ToList();
            
            return View(categories);
        }
        //[ChildActionOnly]
        //public ActionResult CategoryMenu()
        //{
        //    var categories = storeDB.Categories.ToList();
        //    return PartialView(categories);

        //}
        public ActionResult Browse(string category)
        {
            var categoryModel = storeDB.Categories.Include("Items").Single(c => c.Name == category);
            return View(categoryModel);
        }
        public ActionResult Details(int id)
        {
            var Item = storeDB.Items.Find(id);
            return View(Item);
        }
    }
}

Groupy/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Groupy/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Groupy/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="themeSlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#themeSlider" data-slide-to="0" class="active"></li>
        <li data-target="#themeSlider" data-slide-to="1"></li>
        <li data-target="#themeSlider" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner">
        <div class="item active">
            <div class="imgOverlay"></div>
            <img style="height:400px;" src="https://i.guim.co.uk/img/media/2c19c3b2fcbb78358eb734c8cba2bfb02388df0a/0_92_1750_1050/master/1750.jpg?width=445&quality=45&auto=format&fit=max&dpr=2&s=253fee8b29eb5274ee433b788e34ede3" alt="First slide">
            <div class="carousel-caption">
                <h3></h3>
                <p></p>
            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:400px;" src="https://th.bing.com/th/id/R.c8cae556e6b1791f07022e2e2885411b?rik=hlvC9LPPOx1jig&pid=ImgRaw" alt="Second slide">
            <div class="carousel-caption">
                <h3></h3>
                <p></p>
            </div>
        </div>
        <div class="item">
            <div class="imgOverlay"></div>
            <img style="height:400px; width:400px;" src="https://th.bing.com/th/id/OIP.h57TswrkyeEWHqN_9iVa9AHaFj?pid=ImgDet&rs=1" alt="Third slide">
            <div class="carousel-caption">
                <h3></h3>
                <p></p>
            </div>
        </div>
    </div>

    <a class="left carousel-control" href="#themeSlider" data-slide="prev">
        <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#themeSlider" data-slide="next">
        <span class="fa fa-chevron-right"></span>
    </a>

</div>
<h3>Treding Items!</h3>
<ul id="item-list">

    @foreach (var item in Model)
    {

        <li>
            <a href="@Url.Action("Details","Store",new { id = item.ItemId })">
                <img alt="@item.Title" src="@item.ItemArtUrl" />
                <br />

                <span>@item.Title</span>
            </a>

            @String.Format("{0:F}", item.Price)
            <p class="button1">

                @Html.ActionLink("Add to cart", "AddToCart",
        "ShoppingCart", new { id = item.ItemId }, "")
            </p>
        </li>



    }


</ul>